# in _config.yml
title: "Good research code"

execute:
  execute_notebooks: "cache"

repository:
  url                       : https://github.com/patrickmineault/repl-test  # Online location of your book
  path_to_book              : docs/  # Optional path to your book, relative to the repository root
  branch                    : main  # Which branch of the repository should be used when creating links (optional)

launch_buttons:
  thebe        : true
  binderhub_url: https://mybinder.org
  colab_url: "https://colab.research.google.com"
  notebook_interface: "classic" 

html:
  favicon: images/favicon.ico
  home_page_in_navbar: false
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  baseurl: https://localhost:8888/_build
