# in _config.yml
title: "Good research code"
execute:
  execute_notebooks: "off"

repository:
  url                       : https://github.com/patrickmineault/repl-test  # Online location of your book
  path_to_book              : .  # Optional path to your book, relative to the repository root
  branch                    : main  # Which branch of the repository should be used when creating links (optional)